Explicitly define python2 instead of python
If python3 is the default you will get exceptions like:

      File "./weevely.py", line 56
        except ModuleException, e:
                              ^
    SyntaxError: invalid syntax